/* OMABFC x86_64 Linux Assembly code generator */

#include "cgx86_64lin.h"
#include <stdlib.h>

#define MEMSET_REGISTER "rax"       /* Register used to 0 the tape */
#define TAPE_POINTER_REGISTER "rsi" /* pointer used to hold current tape element address */

static void generate_symbol(struct symbol_data* data, FILE* output, int* loop_counter);

static void generate_vinc(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;
    
    if (amount == 1)
        fprintf(output, "    inc byte [" TAPE_POINTER_REGISTER "]\n");
    else
        fprintf(output, "    add " TAPE_POINTER_REGISTER ", %u\n", amount);
}

static void generate_vdec(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    if (amount == 1)
        fprintf(output, "    dec byte [" TAPE_POINTER_REGISTER "]\n");
    else
        fprintf(output, "    sub byte [" TAPE_POINTER_REGISTER "], %u\n", amount);
}

static void generate_pinc(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    if (amount == 1)
        fprintf(output, "    inc " TAPE_POINTER_REGISTER "\n");
    else
        fprintf(output, "    add " TAPE_POINTER_REGISTER ", %u\n", amount);
}

static void generate_pdec(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    if (amount == 1)
        fprintf(output, "    dec " TAPE_POINTER_REGISTER "\n");
    else
        fprintf(output, "    sub " TAPE_POINTER_REGISTER ", %u\n", amount);
}

static void generate_out(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    fprintf(output, "    mov rax, 1\n");
    fprintf(output, "    mov rdi, 1\n");
    fprintf(output, "    mov rdx, 1\n");
    for (int i = 0; i < amount; i++)
    {
        fprintf(output, "    syscall\n\n");
    } 
}

static void generate_in(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    fprintf(output, "    mov rax, 0\n");
    fprintf(output, "    mov rdi, 0\n");
    fprintf(output, "    mov rdx, 1\n");
    for (int i = 0; i < amount; i++)
    {
        fprintf(output, "    syscall\n\n");
    } 
}

static void generate_loop(FILE* output, struct symbol_data* loop_symbol, int* loop_counter)
{
    int used_loop = (*loop_counter)++;
    fprintf(output, "loop%u:\n", used_loop);
    fprintf(output, "    cmp byte [" TAPE_POINTER_REGISTER "], 0\n");
    fprintf(output, "    je loopend%u\n", used_loop);

    struct symbol_data* current = loop_symbol->loop_data.loop_start;
    while (current)
    {
        generate_symbol(current, output, loop_counter);
        current = current->next;
    }

    fprintf(output, "    cmp byte [" TAPE_POINTER_REGISTER "], 0\n");
    fprintf(output, "    jne loop%u\n", used_loop);
    fprintf(output, "loopend%u:\n", used_loop);
}

static void generate_entry(FILE* output, struct codegen_options* options)
{
    fprintf(output, "; Generated by OMABFC x86_64lin codegen\n\n    BITS 64\n\n");
    fprintf(output, "section .bss\n");
    fprintf(output, "    tape resb %d\n\n", options->tape_size);
    fprintf(output, "section .text\n\n");
    fprintf(output, "global _start\n");
    fprintf(output, "_start:\n");
    fprintf(output, "    mov " TAPE_POINTER_REGISTER ", tape\n");
    fprintf(output, "    mov " MEMSET_REGISTER ", %d\n", options->tape_size);
    fprintf(output, "memset_loop:\n");
    fprintf(output, "    cmp " MEMSET_REGISTER ", 0\n");
    fprintf(output, "    je program\n");
    fprintf(output, "    mov byte [tape + " MEMSET_REGISTER "], 0\n");
    fprintf(output, "    dec " MEMSET_REGISTER "\n");
    fprintf(output, "    jmp memset_loop\n");
    fprintf(output, "program:\n");
}

static void generate_exit(FILE* output)
{
    fprintf(output, "    mov rax, 60\n");
    fprintf(output, "    mov rdi, 0\n");
    fprintf(output, "    syscall\n\n");
}

static void generate_symbol(struct symbol_data* data, FILE* output, int* loop_counter)
{
    switch (data->type)
    {
        case SYMBOL_NONE:
            break;
        case SYMBOL_IN:
            generate_in(output, data->amount);
            break;
        case SYMBOL_OUT:
            generate_out(output, data->amount);
            break;
        case SYMBOL_VINC:
            generate_vinc(output, data->amount);
            break;
        case SYMBOL_VDEC:
            generate_vdec(output, data->amount);
            break;
        case SYMBOL_PINC:
            generate_pinc(output, data->amount);
            break;
        case SYMBOL_PDEC:
            generate_pdec(output, data->amount);
            break;
        case SYMBOL_LSTART:
            generate_loop(output, data, loop_counter);
            break;
        default:
            fprintf(stderr, "ERROR: Unknown symbol %d (%c)\n", data->type, data->type);
            exit(1);
            break;
    }
}

void generate_code_x86_64lin(struct symbol_data* data, FILE* output, struct codegen_options options)
{
    int* loop_counter = malloc(sizeof(int));

    /* Generate the initial code template */
    generate_entry(output, &options);

    while (data)
    {
        generate_symbol(data, output, loop_counter);
        data = data->next;
    }

    /* And the exit syscall... */
    generate_exit(output);
    free(loop_counter);
}