/* OMABFC x86_16 DOS Assembly code generator */

#include "cgx86_16dos.h"
#include <stdlib.h>

#define MEMSET_REGISTER "di"        /* Register used to 0 the tape */
#define TAPE_POINTER_REGISTER "si"  /* pointer used to hold current tape element address */

static void generate_symbol(struct symbol_data* data, FILE* output, int* loop_counter);

static void generate_vinc(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;
    
    if (amount == 1)
        fprintf(output, "    inc byte [" TAPE_POINTER_REGISTER "]\n");
    else
        fprintf(output, "    add " TAPE_POINTER_REGISTER ", %u\n", amount);
}

static void generate_vdec(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    if (amount == 1)
        fprintf(output, "    dec byte [" TAPE_POINTER_REGISTER "]\n");
    else
        fprintf(output, "    sub byte [" TAPE_POINTER_REGISTER "], %u\n", amount);
}

static void generate_pinc(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    if (amount == 1)
        fprintf(output, "    inc " TAPE_POINTER_REGISTER "\n");
    else
        fprintf(output, "    add " TAPE_POINTER_REGISTER ", %u\n", amount);
}

static void generate_pdec(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    if (amount == 1)
        fprintf(output, "    dec " TAPE_POINTER_REGISTER "\n");
    else
        fprintf(output, "    sub " TAPE_POINTER_REGISTER ", %u\n", amount);
}

static void generate_out(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    fprintf(output, "    mov ah, 0x02\n");
    fprintf(output, "    mov dl, byte [" TAPE_POINTER_REGISTER "]\n");
    for (int i = 0; i < amount; i++)
    {
        fprintf(output, "    int 0x21\n\n");
    } 
}

static void generate_in(FILE* output, unsigned int amount)
{
    if (amount == 0)
        return;

    fprintf(output, "    mov ah, 0x08\n");
    for (int i = 0; i < amount; i++)
    {
        fprintf(output, "    int 0x21\n");
    } 
    fprintf(output, "    mov byte [" TAPE_POINTER_REGISTER "], al\n\n");
}

static void generate_loop(FILE* output, struct symbol_data* loop_symbol, int* loop_counter)
{
    int used_loop = (*loop_counter)++;
    fprintf(output, "loop%u:\n", used_loop);
    fprintf(output, "    cmp byte [" TAPE_POINTER_REGISTER "], 0\n");
    fprintf(output, "    je loopend%u\n", used_loop);

    struct symbol_data* current = loop_symbol->loop_data.loop_start;
    while (current)
    {
        generate_symbol(current, output, loop_counter);
        current = current->next;
    }

    fprintf(output, "    cmp byte [" TAPE_POINTER_REGISTER "], 0\n");
    fprintf(output, "    jne loop%u\n", used_loop);
    fprintf(output, "loopend%u:\n", used_loop);
}

static void generate_entry(FILE* output)
{
    fprintf(output, "; Generated by OMABFC x86_16dos codegen\n\n    BITS 16\n\n");
    fprintf(output, "section .text\n");
    fprintf(output, "    mov " TAPE_POINTER_REGISTER ", tape\n");
    fprintf(output, "program:\n");
}

static void generate_exit(FILE* output, struct codegen_options* options)
{
    fprintf(output, "    mov ah, 0x4C\n");
    fprintf(output, "    mov al, 0\n");
    fprintf(output, "    int 0x21\n\n");

    fprintf(output, "section .data\n");
    fprintf(output, "    tape times %d db 0\n", options->tape_size);
}

static void generate_symbol(struct symbol_data* data, FILE* output, int* loop_counter)
{
    switch (data->type)
    {
        case SYMBOL_NONE:
            break;
        case SYMBOL_IN:
            generate_in(output, data->amount);
            break;
        case SYMBOL_OUT:
            generate_out(output, data->amount);
            break;
        case SYMBOL_VINC:
            generate_vinc(output, data->amount);
            break;
        case SYMBOL_VDEC:
            generate_vdec(output, data->amount);
            break;
        case SYMBOL_PINC:
            generate_pinc(output, data->amount);
            break;
        case SYMBOL_PDEC:
            generate_pdec(output, data->amount);
            break;
        case SYMBOL_LSTART:
            generate_loop(output, data, loop_counter);
            break;
        default:
            fprintf(stderr, "ERROR: Unknown symbol %d (%c)\n", data->type, data->type);
            exit(1);
            break;
    }
}

void generate_code_x86_16dos(struct symbol_data* data, FILE* output, struct codegen_options options)
{
    int* loop_counter = malloc(sizeof(int));

    /* Generate the initial code template */
    generate_entry(output);

    while (data)
    {
        generate_symbol(data, output, loop_counter);
        data = data->next;
    }

    /* And the exit syscall... */
    generate_exit(output, &options);
    free(loop_counter);
}